export declare const kHundredPercent = "100%";
export declare const kZero = "0";
export declare const kPlus = "+";
export declare const kMinus = "-";
export declare const kPercentage = "%";
export declare const kPixel = "px";
export declare const kTranslateX = "translateX";
export declare const kAnimatedClass = "Animated";
export declare const kTransitionEnd = "transitionend";
export declare const kTouchStart = "touchstart";
export declare const kTouchMove = "touchmove";
export declare const kTouchEnd = "touchend";
//# sourceMappingURL=constants.d.ts.map